# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vrRecord',
            fields=[
                ('vrID', models.AutoField(primary_key=True, serialize=False)),
                ('audioFile', models.TextField()),
                ('textFile', models.TextField()),
            ],
        ),
    ]
