# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vrApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrrecord',
            name='textRealFile',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
