# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 03:00
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import vrApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('vrApp', '0002_auto_20170310_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrrecord',
            name='audioFileRes',
            field=vrApp.models.BlobField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
